# Generated by Django 4.0.2 on 2022-04-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainSGPMS', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
