# Generated by Django 4.0.2 on 2022-04-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSGPMS', '0002_delete_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newvisitor',
            name='approval',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newvisitor',
            name='exit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
