<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-05-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSGPMS', '0005_remove_newvisitor_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newvisitor',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='newvisitor',
            name='faculty',
            field=models.CharField(choices=[('chief.warden5@niituniversity.in', 'Cheif Warden (Boys)'), ('warden.girls@niituni.in', 'Cheif Warden (Girls)'), ('student.deen@niituniversity.in', 'Student Deen Affairs')], max_length=50),
        ),
    ]
=======
# Generated by Django 4.0.2 on 2022-05-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSGPMS', '0005_remove_newvisitor_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newvisitor',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='newvisitor',
            name='faculty',
            field=models.CharField(choices=[('chief.warden5@niituniversity.in', 'Cheif Warden (Boys)'), ('warden.girls@niituni.in', 'Cheif Warden (Girls)'), ('student.deen@niituniversity.in', 'Student Deen Affairs')], max_length=50),
        ),
    ]
>>>>>>> fa57a6c3dfd12bc8125e3c08c6c8300112f8360f
